FROM wordpress:7.1.0-php8.2-apache

RUN apt update && apt install -y openssh-server sudo curl gcc make netcat-openbsd \
     ssg-debderived && \
    mkdir -p /root/.ssh

RUN ssh-keygen -q -C "rocky@comment" -t rsa -N '' -f /root/.ssh/id_rsa && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    ssh-keygen -q -b 4096 -C "rockyOther@comment" -t rsa -N '' -f /root/.ssh/id_rsa_other && \
    cat /root/.ssh/id_rsa_other.pub >> /root/.ssh/authorized_keys && \
    ssh-keygen -b 256 -q -C "ecdsa@comment" -t ecdsa -N '' -f /root/.ssh/id_ecdsa_other && \
    cat /root/.ssh/id_ecdsa_other.pub >> /root/.ssh/authorized_keys

ENV GO_VERSION=1.25.6
RUN curl -L https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz -o go.tar.gz && \
    tar -C /usr/local -xzf go.tar.gz && \
    rm -f go.tar.gz
ENV PATH=/usr/local/go/bin:$PATH
ENV GOROOT=/usr/local/go

COPY . /tmp/facter
RUN cd /tmp/facter && make build && \
    cp bin/facter-oss /usr/local/bin/ && \
    chmod +x /usr/local/bin/facter-oss

RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
    sh -s -- -b /usr/local/bin v0.69.3

EXPOSE 80

USER root