facter:
  enabled: true
  store:
    path: "/tmp/facter-store.db"
  logs:
    debugMode: false
  performanceProfiling:
    enabled: false
  sink:
    enabled: true
    output:
      enabled: true
      format: "proto"
      type: "file"
      outputDirectory: "/tmp"
      outputFilename: "export.iya"
  inventory:
    applications:
      enabled: true
      docker:
        enabled: true
    systemdService:
      enabled: true
    networks:
      enabled: true
      geoIp:
        enabled: true
        timeout: 10
        googleGeoUrl: "https://www.googleapis.com/geolocation/v1/geolocate"
        googleGeoApikey: "AIzaSyB9i6aHGUa5Iv0tfDb9sy_HqXUebFmk8wI"
      ports:
        enabled: true
      publicIp:
        enabled: true
        publicIpApiUrl: "https://ifconfig.me/"
        timeout: 15
      firewall:
        enabled: true
      connections:
        enabled: true
    platform:
      enabled: true
      system:
        initCheckPath: "/proc/1/exe"
        machineID: "/etc/machine-id"
        machineUUID: "/sys/class/dmi/id/product_uuid"
      hardware:
        enabled: true
      os:
        enabled: true
      virtualization:
        enabled: true
      kernel:
        enabled: true
    packages:
      enabled: true
    process:
      enabled: false
    ssh:
      enabled: true
    user:
      enabled: true
      passwdFile: "/etc/passwd"