facter:
  enabled: true
  store:
    path: "/tmp/facter-store.db"
  logs:
    debugMode: true
  performanceProfiling:
    enabled: false
  sink:
    output:
      format: "proto"
      type: "remote"  # local or remote
      outputDirectory: "/tmp"
      outputFilename: "export.iya"
      facterServer: # use it if output.type is remote
        serverHost: localhost
        serverPort: "56230"
        certificatePath: "./certs/facter_cert.pem"
        certificateKeyPath: "./certs/facter_key.pem"
        caPath: "./certs/ca_cert.pem"
        sslHostname: "grpc.test.facter.fr"
  inventory:
    applications:
      enabled: false
      docker:
        enabled: true
    systemdService:
      enabled: false
    networks:
      enabled: false
      geoIp:
        enabled: true
        timeout: 10
        googleGeoUrl: "https://www.googleapis.com/geolocation/v1/geolocate"
        googleGeoApikey: "AIzaSyB9i6aHGUa5Iv0tfDb9sy_HqXUebFmk8wI"
      ports:
        enabled: true
      publicIp:
        enabled: true
        publicIpApiUrl: "https://ifconfig.me/"
        timeout: 15
      firewall:
        enabled: true
      connections:
        enabled: true
    platform:
      enabled: true
      system:
        initCheckPath: "/proc/1/exe"
        machineID: "/etc/machine-id"
        machineUUID: "/sys/class/dmi/id/product_uuid"
      hardware:
        enabled: true
      os:
        enabled: true
      virtualization:
        enabled: true
      kernel:
        enabled: true
    packages:
      enabled: false
    process:
      enabled: false
    ssh:
      enabled: false
    user:
      enabled: false
      passwdFile: "/etc/passwd"
  compliance:
    enabled: false
    profile: "xccdf_org.ssgproject.content_profile_cis_level1_server"
    resultFile: "/tmp/openscap-results.xml"
  vulnerabilities:
    enabled: false