name: Go
permissions:
  contents: read
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: go build -mod=vendor -v ./...
      - name: Test with the Go CLI
        run: go test -mod=vendor -cover -race -v ./...
